### ISSUE TITLE
Why do we have a ppp branch as the default branch instead of the gh-pages branch?

### ISSUE THREAD

**Issue by jpmckinney** [open-contracting/ocds-show-ppp#2]
https://github.com/open-contracting/ocds-show-ppp/compare/ppp...gh-pages?expand=1

From https://github.com/open-contracting/standard-development-handbook/issues/3

**Comment by jpmckinney** [comment]
Or rather, why do we have a `ppp` branch as the default branch instead of the `gh-pages` branch?

**Comment by jpmckinney** [comment]
Changed issue title with respect to last comment.

**Comment by kindly** [comment]
No real reason. The ppp branch and the gh-pages branch in this repo are intended to be kept in sync.  

I think I chose the ppp branch though as if there were any pull requests in this repo they could go to that branch instead of "going live" straight away.  

This repo should now be a copy of ocds-show repo (it did not used to be though) and exists just for the gh-pages branch and all development should be on the ocds-show repo anyway.
Perhaps the ppp branch should be deleted and only have the the gh-pages for clarity.

**Comment by jpmckinney** [comment]
Could we:

* [x] Change default branch to gh-pages
* [x] Delete ppp branch
* [x] Update/replace readme to describe relationship between this repo and ocds-show

?

**Comment by kindly** [comment]
@jpmckinney sounds good to me. I have not access change default branch but can do other two.

**Comment by jpmckinney** [comment]
Ah, true, did that now.

**Comment by robredpath** [comment]
I'll delete the branch and update the README.

**Comment by robredpath** [comment]
https://github.com/open-contracting/ocds-show-ppp/pull/5

**Comment by jpmckinney** [comment]
Done via #5.
